import json

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🧬 MTase Topology Analyzer\n",
    "\n",
    "**Automatic analysis and classification of DNA methyltransferases based on beta-sheet topology**\n",
    "\n",
    "---\n",
    "## ⚡ Setup (Run This Cell First)\n",
    "\n",
    "This cell clones the repository and installs all dependencies."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {},
   "outputs": [],
   "source": [
    "# @title Setup\n",
    "\n",
    "import os\n",
    "import pandas as pd\n",
    "from IPython.display import display, HTML, Markdown\n",
    "\n",
    "print(\"🚀 Setting up MTase Topology Analyzer...\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "# Clone repository\n",
    "if not os.path.exists(\"MTase_topology_analyser\"):\n",
    "    !git clone https://github.com/MVolobueva/MTase_topology_analyser.git\n",
    "    print(\"✅ Repository cloned\")\n",
    "else:\n",
    "    print(\"✅ Repository already exists\")\n",
    "\n",
    "os.chdir(\"MTase_topology_analyser\")\n",
    "\n",
    "# Install dependencies\n",
    "print(\"\\n📦 Installing Python dependencies...\")\n",
    "!pip install -q streamlit pandas numpy scipy biopython plotly py3dmol\n",
    "\n",
    "print(\"\\n✅ Setup complete!\")\n",
    "print(\"=\" * 60)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "## 🎛️ Option 1: Interactive Web App (Recommended)\n",
    "\n",
    "Launches a full web interface with 3D visualization. Click the link that appears below."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {},
   "outputs": [],
   "source": [
    "# @title Run Web App\n",
    "\n",
    "import time\n",
    "import subprocess\n",
    "\n",
    "print(\"🚀 Launching Streamlit Web App...\")\n",
    "\n",
    "# Kill any existing streamlit processes\n",
    "!pkill -f streamlit 2>/dev/null\n",
    "\n",
    "# Launch Streamlit\n",
    "!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false --browser.gatherUsageStats false &\n",
    "\n",
    "time.sleep(5)\n",
    "\n",
    "# Show the URL\n",
    "from google.colab import output\n",
    "output.serve_kernel_port_as_window(8501)\n",
    "\n",
    "display(HTML(\"\"\"\n",
    "<div style=\"background-color: #d4edda; padding: 15px; border-radius: 10px; margin: 10px 0;\">\n",
    "    <h3>✅ Streamlit App is Running!</h3>\n",
    "    <p>Click the link above to open the MTase Topology Analyzer.</p>\n",
    "    <p><small>If the link doesn't work, go to the <b>Ports</b> tab (🔌) and click the 🌐 icon next to port 8501.</small></p>\n",
    "</div>\n",
    "\"\"\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "## 📊 Option 2: Batch Analysis from CSV\n",
    "\n",
    "Upload a CSV file with structures to analyze. Results will be displayed and available for download.\n",
    "\n",
    "**CSV format:**\n",
    "```csv\n",
    "ID,Type\n",
    "3S1S,pdb\n",
    "A0A7R8ZSU6,alphafold\n",
    "/path/to/file.pdb,file\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {},
   "outputs": [],
   "source": [
    "# @title Run Batch Analysis\n",
    "\n",
    "from google.colab import files\n",
    "import pandas as pd\n",
    "import io\n",
    "\n",
    "upload_csv = False  # @param {type:\"boolean\"}\n",
    "\n",
    "if upload_csv:\n",
    "    print(\"📁 Please upload your CSV file\")\n",
    "    uploaded = files.upload()\n",
    "    \n",
    "    for filename in uploaded.keys():\n",
    "        print(f\"\\n📊 Analyzing {filename}...\")\n",
    "        \n",
    "        # Run batch analyzer\n",
    "        !python batch_analyze.py {filename} results.csv\n",
    "        \n",
    "        # Display results\n",
    "        df = pd.read_csv('results.csv')\n",
    "        display(Markdown(f\"### 📊 Results for {filename}\"))\n",
    "        display(df)\n",
    "        \n",
    "        # Download button\n",
    "        files.download('results.csv')\n",
    "else:\n",
    "    print(\"Set upload_csv = True to upload and analyze a CSV file\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "## 🔬 Option 3: Quick Single Structure Analysis\n",
    "\n",
    "Enter a PDB ID or AlphaFold ID below to analyze a single structure."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {},
   "outputs": [],
   "source": [
    "# @title Run Single Structure Analysis\n",
    "\n",
    "from analyzer import MTaseAnalyzer\n",
    "from utils.helpers import download_structure\n",
    "from classifier import classify_topology\n",
    "import sys\n",
    "import io\n",
    "\n",
    "def analyze_single(id_value, source_type):\n",
    "    print(f\"\\n🔬 Analyzing: {id_value} ({source_type})\")\n",
    "    print(\"-\" * 50)\n",
    "    \n",
    "    try:\n",
    "        if source_type == 'pdb':\n",
    "            result_files = download_structure(id_value, source='pdb')\n",
    "        elif source_type == 'alphafold':\n",
    "            result_files = download_structure(id_value, source='alphafold')\n",
    "        else:\n",
    "            print(\"   Unsupported source type\")\n",
    "            return None\n",
    "        \n",
    "        if not result_files:\n",
    "            print(f\"   ❌ Failed to load {id_value}\")\n",
    "            return None\n",
    "        \n",
    "        analyzer = MTaseAnalyzer()\n",
    "        if not analyzer.load_dssp(result_files['dssp']):\n",
    "            print(f\"   ❌ Failed to load DSSP\")\n",
    "            return None\n",
    "        \n",
    "        analyzer.find_all_strands()\n",
    "        analyzer.build_sheet_adjacency()\n",
    "        \n",
    "        motifs = analyzer.find_all_motifs()\n",
    "        motifs = analyzer.filter_motifs_by_topology(motifs)\n",
    "        \n",
    "        if not motifs:\n",
    "            print(f\"   ⚠️ No motifs found\")\n",
    "            return None\n",
    "        \n",
    "        results = []\n",
    "        for motif_data in motifs:\n",
    "            chain = motif_data['chain']\n",
    "            motif_text = motif_data['text']\n",
    "            motif_res = motif_data['res']\n",
    "            motif_position = f\"{motif_res}-{motif_res + len(motif_text) - 1}\"\n",
    "            \n",
    "            result = analyzer.analyze_topology(motif_data=motif_data)\n",
    "            if not result:\n",
    "                continue\n",
    "            \n",
    "            # Get topology string\n",
    "            old_stdout = sys.stdout\n",
    "            new_stdout = io.StringIO()\n",
    "            sys.stdout = new_stdout\n",
    "            analyzer.print_linear_topology_from_result(result)\n",
    "            sys.stdout = old_stdout\n",
    "            \n",
    "            topology_str = new_stdout.getvalue()\n",
    "            lines = topology_str.strip().split('\\n')\n",
    "            topology_line = \"\"\n",
    "            for line in lines:\n",
    "                if ('↑' in line or '↓' in line) and '[' in line and ']' in line:\n",
    "                    topology_line = line.strip()\n",
    "                    break\n",
    "            \n",
    "            if not topology_line:\n",
    "                continue\n",
    "            \n",
    "            classification = classify_topology(topology_line, motif_text)\n",
    "            \n",
    "            results.append({\n",
    "                'Chain': chain,\n",
    "                'Motif': motif_text,\n",
    "                'Position': motif_position,\n",
    "                'Class': classification['class'],\n",
    "                'Confidence': classification['confidence'],\n",
    "                'Strand Order': classification['strand_order'],\n",
    "                'Has S0': classification['has_s0'],\n",
    "                'Has S-1': classification['has_s-1'],\n",
    "                'Gap S6-S7': classification['gap_s6_s7']\n",
    "            })\n",
    "        \n",
    "        if results:\n",
    "            df = pd.DataFrame(results)\n",
    "            display(Markdown(f\"### 📊 Results for {id_value}\"))\n",
    "            display(df)\n",
    "            return results\n",
    "        else:\n",
    "            print(f\"   ⚠️ No valid topology found\")\n",
    "            return None\n",
    "            \n",
    "    except Exception as e:\n",
    "        print(f\"   ❌ Error: {str(e)}\")\n",
    "        return None\n",
    "\n",
    "# @markdown ---\n",
    "# @markdown Enter the structure ID below:\n",
    "structure_id = \"3S1S\"  # @param {type:\"string\"}\n",
    "structure_type = \"pdb\"  # @param [\"pdb\", \"alphafold\"]\n",
    "\n",
    "analyze_single(structure_id, structure_type)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "## 📖 Help & Documentation\n",
    "\n",
    "### Output Columns\n",
    "\n",
    "| Column | Description |\n",
    "|--------|-------------|\n",
    "| Chain | Chain identifier (A, B, C, etc.) |\n",
    "| Motif | Catalytic motif (NPPY, DPPY, GPPC, etc.) |\n",
    "| Class | Structural class (A/B/C/D/E/F) |\n",
    "| Strand Order | Order of beta-strands in N->C direction |\n",
    "| Gap S6-S7 | Distance between strands S6 and S7 |\n",
    "\n",
    "### Links\n",
    "- [GitHub Repository](https://github.com/MVolobueva/MTase_topology_analyser)\n",
    "- [Report Issues](https://github.com/MVolobueva/MTase_topology_analyser/issues)\n",
    "\n",
    "### Contact\n",
    "M. Samokhina – mashila6799@gmail.com"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "provenance": [],
   "toc_visible": True
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

# Save the notebook
with open('MTase_Topology_Analyzer.ipynb', 'w') as f:
    json.dump(notebook_content, f, indent=1)

print("✅ Notebook created: MTase_Topology_Analyzer.ipynb")